openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: AZPay Checkout Evaluation API
    url: https://evaluation.checkout.azpay.com.br/api/v1
info:
  description: This is AZPay Checkout API
  version: "1.0.0"
  title: AZPay Checkout API
  contact:
    email: contato@azpay.com.br
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths:
  $ref: ./paths/index.yaml